# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('ddd', models.CharField(max_length=3)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.Estado')),
            ],
        ),
    ]
