# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0003_auto_20170130_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=256)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Cidade')),
            ],
            options={
                'verbose_name_plural': 'Fabricantes',
                'verbose_name': 'Fabricante',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Fabricante')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
                'verbose_name': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('nome', models.CharField(max_length=64)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Marca')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
                'verbose_name': 'Produto',
            },
        ),
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together=set([('nome', 'fabricante')]),
        ),
    ]
