# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20170130_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Estoque de Produtos',
                'verbose_name': 'Estoque',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('data_validade', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Lotes',
                'verbose_name': 'Lote',
            },
        ),
        migrations.CreateModel(
            name='Prateleira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Prateleiras',
                'verbose_name': 'Prateleira',
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Categoria'),
        ),
        migrations.AddField(
            model_name='lote',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Produto'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Lote'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='prateleira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Prateleira'),
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together=set([('lote', 'prateleira')]),
        ),
    ]
